# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ConnectionStrings:TeleAPI: $(TeleAPI)
  ConnectionStrings:SmtpUsername: $(SmtpUsername)
  ConnectionStrings:SmtpPassword: $(SmtpPassword)
  ConnectionStrings:PostgresqlProd: $(PostgresqlProd)
  ConnectionStrings:PComNetUsername: $(PComNetUsername)
  ConnectionStrings:PComNetPassword: $(PComNetPassword)
  ConnectionStrings:BulkVSAPISecret: $(BulkVSAPISecret)
  ConnectionStrings:BulkVSAPIKEY: $(BulkVSAPIKEY)
  ApplicationInsights:InstrumentationKey: $(InstrumentationKey)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: FileTransform@2
  
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Mvc/' 
    jsonTargetFiles: appsettings.json
    xmlTransformationRules: '' # disabled

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'

