# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  ConnectionStrings.TeleAPI: $(TeleAPI)
  ConnectionStrings.SmtpUsername: $(SmtpUsername)
  ConnectionStrings.SmtpPassword: $(SmtpPassword)
  ConnectionStrings.PostgresqlProd: $(PostgresqlProd)
  ConnectionStrings.PComNetUsername: $(PComNetUsername)
  ConnectionStrings.PComNetPassword: $(PComNetPassword)
  ConnectionStrings.PeerlessAPIKey: $(PeerlessAPIKey)
  ConnectionStrings.BulkVSAPISecret: $(BulkVSAPISecret)
  ConnectionStrings.ChannelGroup: $(ChannelGroup)
  ConnectionStrings.CallFlow: $(CallFlow)
  ConnectionStrings.BulkVSAPIKEY: $(BulkVSAPIKEY)
  ConnectionStrings.BulkVSUsername: $(BulkVSUsername)
  ConnectionStrings.BulkVSPassword: $(BulkVSPassword)
  ConnectionStrings.MicrosoftClientSecret: $(MicrosoftClientSecret)
  ConnectionStrings.MicrosoftClientId: $(MicrosoftClientId)
  ConnectionStrings.InvoiceNinjaToken: $(InvoiceNinjaToken)
  ConnectionStrings.Data247Username: $(Data247Username)
  ConnectionStrings.Data247Password: $(Data247Password)
  ConnectionStrings.EmailOrders: $(EmailOrders)
  ConnectionStrings.EmailDan: $(EmailDan)
  ConnectionStrings.EmailTom: $(EmailTom)
  ApplicationInsights.InstrumentationKey: $(InstrumentationKey)

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Tests/bin/Release/net5.0/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Mvc/bin/Release/net5.0/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Ingest/bin/Release/net5.0/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Ops/bin/Release/net5.0/'
    jsonTargetFiles: 'appsettings.json'
    xmlTransformationRules: '' # disabled

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'Mvc'
    targetPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Mvc/bin/Release/net5.0/'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'Ingest'
    targetPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Ingest/bin/Release/net5.0/'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: 'Ops'
    targetPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Ops/bin/Release/net5.0/'
    publishLocation: 'pipeline'