# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  ConnectionStrings.TeleAPI: $(TeleAPI)
  ConnectionStrings.SmtpUsername: $(SmtpUsername)
  ConnectionStrings.SmtpPassword: $(SmtpPassword)
  ConnectionStrings.PostgresqlProd: $(PostgresqlProd)
  ConnectionStrings.PComNetUsername: $(PComNetUsername)
  ConnectionStrings.PComNetPassword: $(PComNetPassword)
  ConnectionStrings.PeerlessAPIKey: $(PeerlessAPIKey)
  ConnectionStrings.ChannelGroup: $(ChannelGroup)
  ConnectionStrings.CallFlow: $(CallFlow)
  ConnectionStrings.BulkVSAPISecret: $(BulkVSAPISecret)
  ConnectionStrings.BulkVSAPIKEY: $(BulkVSAPIKEY)
  ConnectionStrings.InvoiceNinjaToken: $(InvoiceNinjaToken)
  ApplicationInsights.InstrumentationKey: $(InstrumentationKey)

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'  

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/NumberSearch.Tests/bin/Release/netcoreapp3.1/'
    jsonTargetFiles: 'appsettings.json'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'