using Flurl.Http;

using System;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace NumberSearch.DataAccess
{
    // Data source: https://dor.wa.gov/taxes-rates/retail-sales-tax/destination-based-sales-tax-and-streamlined-sales-tax/wa-sales-tax-rate-lookup-url-interface
    // These XML serialization classes were autogenerated by the Edit => Paste Special => Paste XML as Classes command in VS 2019. 
    // Then I cleaned them up to remove the complex getter and setters and the duplicate private fields they required.
    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    [System.Serializable()]
    [System.ComponentModel.DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", ElementName = "response", IsNullable = false)]
    public record SalesTax
    {
        public Addressline addressline { get; set; } = new();
        public Rate rate { get; set; } = new();
        [XmlAttribute()]
        public int loccode { get; set; }
        [XmlAttribute()]
        public decimal localrate { get; set; }
        [XmlAttribute("rate")]
        public decimal rate1 { get; set; }
        [XmlAttribute()]
        public int code { get; set; }

        [System.Serializable()]
        [System.ComponentModel.DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public partial record Addressline
        {
            [XmlAttribute()]
            public int code { get; set; }
            [XmlAttribute()]
            public string street { get; set; } = string.Empty;
            [XmlAttribute()]
            public int househigh { get; set; }
            [XmlAttribute()]
            public int houselow { get; set; }
            [XmlAttribute()]
            public string evenodd { get; set; } = string.Empty;
            [XmlAttribute()]
            public string state { get; set; } = string.Empty;
            [XmlAttribute()]
            public int zip { get; set; }
            [XmlAttribute()]
            public int plus4 { get; set; }
            [XmlAttribute()]
            public string period { get; set; } = string.Empty;
            [XmlAttribute()]
            public string rta { get; set; } = string.Empty;
            [XmlAttribute()]
            public string ptba { get; set; } = string.Empty;
            [XmlAttribute()]
            public string cez { get; set; } = string.Empty;
        }

        [System.Serializable()]
        [System.ComponentModel.DesignerCategory("code")]
        [XmlType(AnonymousType = true)]
        public partial record Rate
        {
            [XmlAttribute()]
            public string name { get; set; } = string.Empty;
            [XmlAttribute()]
            public int code { get; set; }
            [XmlAttribute()]
            public decimal staterate { get; set; }
            [XmlAttribute()]
            public decimal localrate { get; set; }
        }

        public static async Task<SalesTax> GetLocalAPIAsync(ReadOnlyMemory<char> streetAddress, ReadOnlyMemory<char> city, ReadOnlyMemory<char> zip)
        {
            string baseUrl = "https://wataxlookup.acceleratenetworks.com/";
            string endpoint = "AddressRates.aspx";
            string outputParameter = $"?output=xml";
            string addrParameter = $"&addr={streetAddress}";
            string cityParameter = $"&city={city}";
            string zipParameter = $"&zip={zip}";
            string url = $"{baseUrl}{endpoint}{outputParameter}{addrParameter}{cityParameter}{zipParameter}";

            using var result = await url.GetStreamAsync();

            // Learn more about this XML serialization method: https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-deserialize-an-object
            var serializer = new XmlSerializer(typeof(SalesTax));
            return (SalesTax)serializer.Deserialize(result)!;
        }

        /// <summary>
        /// Get the Sale Tax rate for a specific address.
        /// </summary>
        /// <param name="streetAddress"> A valid street address (ex. 6500 Linderson way) </param>
        /// <param name="city"> A valid City name (ex. Seattle) </param>
        /// <param name="zip"> A valid Zip code inside Washington State (ex. 98501) </param>
        /// <returns></returns>
        public static async Task<SalesTax> GetAsync(ReadOnlyMemory<char> streetAddress, ReadOnlyMemory<char> city, ReadOnlyMemory<char> zip)
        {
            string baseUrl = "http://webgis.dor.wa.gov/webapi/";
            string endpoint = "AddressRates.aspx";
            string outputParameter = $"?output=xml";
            string addrParameter = $"&addr={streetAddress}";
            string cityParameter = $"&city={city}";
            string zipParameter = $"&zip={zip}";
            string url = $"{baseUrl}{endpoint}{outputParameter}{addrParameter}{cityParameter}{zipParameter}";

            using var result = await url.GetStreamAsync();

            // Learn more about this XML serialization method: https://docs.microsoft.com/en-us/dotnet/standard/serialization/how-to-deserialize-an-object
            var serializer = new XmlSerializer(typeof(SalesTax));
            return (SalesTax)serializer.Deserialize(result)!;
        }
    }

    public readonly record struct TaxRate(string name, int locationCode, decimal state, decimal local, decimal rta, decimal rate, DateTime effectiveDate, DateTime expirationDate)
    {
        public static async Task<TaxRate> GetSalesTaxAsync(ReadOnlyMemory<char> streetAddress, ReadOnlyMemory<char> city, ReadOnlyMemory<char> zip)
        {
            string baseUrl = "https://wataxlookup.acceleratenetworks.com/";
            string endpoint = "GetTaxRate";
            string addrParameter = $"?addr={streetAddress}";
            string cityParameter = $"&city={city}";
            string zipParameter = $"&zip={zip}";
            string url = $"{baseUrl}{endpoint}{addrParameter}{cityParameter}{zipParameter}";

            var result = await url.GetJsonAsync<TaxRate>();

            return result;
        }
    };
}