//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkVS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:bulkvs", ConfigurationName="BulkVS.bulkvsPort")]
    public interface bulkvsPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#queryAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.queryAccountResponse> queryAccountAsync(BulkVS.queryAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#cdrSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.cdrSearchResponse> cdrSearchAsync(BulkVS.cdrSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#cnamLookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.cnamLookupResponse> cnamLookupAsync(BulkVS.cnamLookupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#smsSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.smsSendResponse> smsSendAsync(BulkVS.smsSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnSearchAreaCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnSearchAreaCodeResponse> DnSearchAreaCodeAsync(BulkVS.DnSearchAreaCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnSearchNpaNxx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnSearchNpaNxxResponse> DnSearchNpaNxxAsync(BulkVS.DnSearchNpaNxxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnOrderResponse> DnOrderAsync(BulkVS.DnOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnUpdateResponse> DnUpdateAsync(BulkVS.DnUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnDeleteResponse> DnDeleteAsync(BulkVS.DnDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnQueryResponse> DnQueryAsync(BulkVS.DnQueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnqueryAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnqueryAllResponse> DnqueryAllAsync(BulkVS.DnqueryAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#DnTrunkGroupList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.DnTrunkGroupListResponse> DnTrunkGroupListAsync(BulkVS.DnTrunkGroupListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#LNPcheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.LNPcheckResponse> LNPcheckAsync(BulkVS.LNPcheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#e911removeRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.e911removeRecordResponse> e911removeRecordAsync(BulkVS.e911removeRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#e911queryRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.e911queryRecordResponse> e911queryRecordAsync(BulkVS.e911queryRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#e911queryAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.e911queryAllResponse> e911queryAllAsync(BulkVS.e911queryAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#e911validateAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.e911validateAddressResponse> e911validateAddressAsync(BulkVS.e911validateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#bulkvs#e911provisionAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<BulkVS.e911provisionAddressResponse> e911provisionAddressAsync(BulkVS.e911provisionAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAccount", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class queryAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        public queryAccountRequest()
        {
        }
        
        public queryAccountRequest(string apikey, string apisecret)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAccountResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class queryAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public queryAccountResponse()
        {
        }
        
        public queryAccountResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cdrSearch", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class cdrSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string startDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string endDate;
        
        public cdrSearchRequest()
        {
        }
        
        public cdrSearchRequest(string apikey, string apisecret, string type, string startDate, string endDate)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.type = type;
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cdrSearchResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class cdrSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public cdrSearchResponse()
        {
        }
        
        public cdrSearchResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cnamLookup", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class cnamLookupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        public cnamLookupRequest()
        {
        }
        
        public cnamLookupRequest(string apikey, string apisecret, string dn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cnamLookupResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class cnamLookupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public cnamLookupResponse()
        {
        }
        
        public cnamLookupResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsSend", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class smsSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string message;
        
        public smsSendRequest()
        {
        }
        
        public smsSendRequest(string apikey, string apisecret, string from, string to, string message)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.from = from;
            this.to = to;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsSendResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class smsSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public smsSendResponse()
        {
        }
        
        public smsSendResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnSearchAreaCode", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnSearchAreaCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string areacode;
        
        public DnSearchAreaCodeRequest()
        {
        }
        
        public DnSearchAreaCodeRequest(string apikey, string apisecret, string areacode)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.areacode = areacode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnSearchAreaCodeResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnSearchAreaCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnSearchAreaCodeResponse()
        {
        }
        
        public DnSearchAreaCodeResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnSearchNpaNxx", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnSearchNpaNxxRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string NpaNxx;
        
        public DnSearchNpaNxxRequest()
        {
        }
        
        public DnSearchNpaNxxRequest(string apikey, string apisecret, string NpaNxx)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.NpaNxx = NpaNxx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnSearchNpaNxxResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnSearchNpaNxxResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnSearchNpaNxxResponse()
        {
        }
        
        public DnSearchNpaNxxResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnOrder", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string trunkgroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cnamlookup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string lidb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string messaging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string portoutpin;
        
        public DnOrderRequest()
        {
        }
        
        public DnOrderRequest(string apikey, string apisecret, string dn, string trunkgroup, string cnamlookup, string lidb, string messaging, string portoutpin)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
            this.trunkgroup = trunkgroup;
            this.cnamlookup = cnamlookup;
            this.lidb = lidb;
            this.messaging = messaging;
            this.portoutpin = portoutpin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnOrderResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnOrderResponse()
        {
        }
        
        public DnOrderResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnUpdate", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string trunkgroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string cnamlookup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string lidb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string messaging;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string portoutpin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string callforward;
        
        public DnUpdateRequest()
        {
        }
        
        public DnUpdateRequest(string apikey, string apisecret, string dn, string trunkgroup, string cnamlookup, string lidb, string messaging, string portoutpin, string callforward)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
            this.trunkgroup = trunkgroup;
            this.cnamlookup = cnamlookup;
            this.lidb = lidb;
            this.messaging = messaging;
            this.portoutpin = portoutpin;
            this.callforward = callforward;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnUpdateResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnUpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnUpdateResponse()
        {
        }
        
        public DnUpdateResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnDelete", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        public DnDeleteRequest()
        {
        }
        
        public DnDeleteRequest(string apikey, string apisecret, string dn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnDeleteResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnDeleteResponse()
        {
        }
        
        public DnDeleteResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnQuery", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        public DnQueryRequest()
        {
        }
        
        public DnQueryRequest(string apikey, string apisecret, string dn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnQueryResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnQueryResponse()
        {
        }
        
        public DnQueryResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnqueryAll", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnqueryAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        public DnqueryAllRequest()
        {
        }
        
        public DnqueryAllRequest(string apikey, string apisecret)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnqueryAllResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnqueryAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnqueryAllResponse()
        {
        }
        
        public DnqueryAllResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnTrunkGroupList", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnTrunkGroupListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        public DnTrunkGroupListRequest()
        {
        }
        
        public DnTrunkGroupListRequest(string apikey, string apisecret)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DnTrunkGroupListResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class DnTrunkGroupListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public DnTrunkGroupListResponse()
        {
        }
        
        public DnTrunkGroupListResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LNPcheck", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class LNPcheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string tn;
        
        public LNPcheckRequest()
        {
        }
        
        public LNPcheckRequest(string apikey, string apisecret, string tn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.tn = tn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LNPcheckResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class LNPcheckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public LNPcheckResponse()
        {
        }
        
        public LNPcheckResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911removeRecord", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911removeRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        public e911removeRecordRequest()
        {
        }
        
        public e911removeRecordRequest(string apikey, string apisecret, string dn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911removeRecordResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911removeRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public e911removeRecordResponse()
        {
        }
        
        public e911removeRecordResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911queryRecord", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911queryRecordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        public e911queryRecordRequest()
        {
        }
        
        public e911queryRecordRequest(string apikey, string apisecret, string dn)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911queryRecordResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911queryRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public e911queryRecordResponse()
        {
        }
        
        public e911queryRecordResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911queryAll", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911queryAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        public e911queryAllRequest()
        {
        }
        
        public e911queryAllRequest(string apikey, string apisecret)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911queryAllResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911queryAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public e911queryAllResponse()
        {
        }
        
        public e911queryAllResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911validateAddress", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911validateAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string address1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string address2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string zip;
        
        public e911validateAddressRequest()
        {
        }
        
        public e911validateAddressRequest(string apikey, string apisecret, string address1, string address2, string city, string state, string zip)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.address1 = address1;
            this.address2 = address2;
            this.city = city;
            this.state = state;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911validateAddressResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911validateAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public e911validateAddressResponse()
        {
        }
        
        public e911validateAddressResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911provisionAddress", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911provisionAddressRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string apikey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string apisecret;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string dn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string callername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string addressid;
        
        public e911provisionAddressRequest()
        {
        }
        
        public e911provisionAddressRequest(string apikey, string apisecret, string dn, string callername, string addressid)
        {
            this.apikey = apikey;
            this.apisecret = apisecret;
            this.dn = dn;
            this.callername = callername;
            this.addressid = addressid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e911provisionAddressResponse", WrapperNamespace="http://schemas.xmlsoap.org/soap/envelope/", IsWrapped=true)]
    public partial class e911provisionAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string result;
        
        public e911provisionAddressResponse()
        {
        }
        
        public e911provisionAddressResponse(string result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface bulkvsPortChannel : BulkVS.bulkvsPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class bulkvsPortClient : System.ServiceModel.ClientBase<BulkVS.bulkvsPort>, BulkVS.bulkvsPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public bulkvsPortClient() : 
                base(bulkvsPortClient.GetDefaultBinding(), bulkvsPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.bulkvsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public bulkvsPortClient(EndpointConfiguration endpointConfiguration) : 
                base(bulkvsPortClient.GetBindingForEndpoint(endpointConfiguration), bulkvsPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public bulkvsPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(bulkvsPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public bulkvsPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(bulkvsPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public bulkvsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BulkVS.queryAccountResponse> queryAccountAsync(BulkVS.queryAccountRequest request)
        {
            return base.Channel.queryAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.cdrSearchResponse> cdrSearchAsync(BulkVS.cdrSearchRequest request)
        {
            return base.Channel.cdrSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.cnamLookupResponse> cnamLookupAsync(BulkVS.cnamLookupRequest request)
        {
            return base.Channel.cnamLookupAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.smsSendResponse> smsSendAsync(BulkVS.smsSendRequest request)
        {
            return base.Channel.smsSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnSearchAreaCodeResponse> DnSearchAreaCodeAsync(BulkVS.DnSearchAreaCodeRequest request)
        {
            return base.Channel.DnSearchAreaCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnSearchNpaNxxResponse> DnSearchNpaNxxAsync(BulkVS.DnSearchNpaNxxRequest request)
        {
            return base.Channel.DnSearchNpaNxxAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnOrderResponse> DnOrderAsync(BulkVS.DnOrderRequest request)
        {
            return base.Channel.DnOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnUpdateResponse> DnUpdateAsync(BulkVS.DnUpdateRequest request)
        {
            return base.Channel.DnUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnDeleteResponse> DnDeleteAsync(BulkVS.DnDeleteRequest request)
        {
            return base.Channel.DnDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnQueryResponse> DnQueryAsync(BulkVS.DnQueryRequest request)
        {
            return base.Channel.DnQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnqueryAllResponse> DnqueryAllAsync(BulkVS.DnqueryAllRequest request)
        {
            return base.Channel.DnqueryAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.DnTrunkGroupListResponse> DnTrunkGroupListAsync(BulkVS.DnTrunkGroupListRequest request)
        {
            return base.Channel.DnTrunkGroupListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.LNPcheckResponse> LNPcheckAsync(BulkVS.LNPcheckRequest request)
        {
            return base.Channel.LNPcheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.e911removeRecordResponse> e911removeRecordAsync(BulkVS.e911removeRecordRequest request)
        {
            return base.Channel.e911removeRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.e911queryRecordResponse> e911queryRecordAsync(BulkVS.e911queryRecordRequest request)
        {
            return base.Channel.e911queryRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.e911queryAllResponse> e911queryAllAsync(BulkVS.e911queryAllRequest request)
        {
            return base.Channel.e911queryAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.e911validateAddressResponse> e911validateAddressAsync(BulkVS.e911validateAddressRequest request)
        {
            return base.Channel.e911validateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<BulkVS.e911provisionAddressResponse> e911provisionAddressAsync(BulkVS.e911provisionAddressRequest request)
        {
            return base.Channel.e911provisionAddressAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.bulkvsPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.bulkvsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.bulkvs.com/api");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return bulkvsPortClient.GetBindingForEndpoint(EndpointConfiguration.bulkvsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return bulkvsPortClient.GetEndpointAddress(EndpointConfiguration.bulkvsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            bulkvsPort,
        }
    }
}
