//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace="tempuri.org")]

namespace tempuri.org
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OCNLATAResult2", Namespace="http://tempuri.org/")]
    public partial class OCNLATAResult2 : tempuri.org.EndstreamBaseObject
    {
        
        private string TNField;
        
        private string ResponseCodeField;
        
        private string LrnField;
        
        private string OcnField;
        
        private string OcntypeField;
        
        private string OcnnameField;
        
        private string NpanxxField;
        
        private string cityField;
        
        private string stateField;
        
        private string lataField;
        
        private string rcAbbrField;
        
        private string lrnCityField;
        
        private string lrnStateField;
        
        private string lrnlataField;
        
        private string DatePortedField;
        
        private string AltSpidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TN
        {
            get
            {
                return this.TNField;
            }
            set
            {
                this.TNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Lrn
        {
            get
            {
                return this.LrnField;
            }
            set
            {
                this.LrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ocn
        {
            get
            {
                return this.OcnField;
            }
            set
            {
                this.OcnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Ocntype
        {
            get
            {
                return this.OcntypeField;
            }
            set
            {
                this.OcntypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ocnname
        {
            get
            {
                return this.OcnnameField;
            }
            set
            {
                this.OcnnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Npanxx
        {
            get
            {
                return this.NpanxxField;
            }
            set
            {
                this.NpanxxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string lata
        {
            get
            {
                return this.lataField;
            }
            set
            {
                this.lataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string rcAbbr
        {
            get
            {
                return this.rcAbbrField;
            }
            set
            {
                this.rcAbbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string lrnCity
        {
            get
            {
                return this.lrnCityField;
            }
            set
            {
                this.lrnCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string lrnState
        {
            get
            {
                return this.lrnStateField;
            }
            set
            {
                this.lrnStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string lrnlata
        {
            get
            {
                return this.lrnlataField;
            }
            set
            {
                this.lrnlataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DatePorted
        {
            get
            {
                return this.DatePortedField;
            }
            set
            {
                this.DatePortedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string AltSpid
        {
            get
            {
                return this.AltSpidField;
            }
            set
            {
                this.AltSpidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndstreamBaseObject", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.OCNLATAResult2))]
    public partial class EndstreamBaseObject : object
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="OCNLATAdipSoap")]
public interface OCNLATAdipSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APITestCall", ReplyAction="*")]
    System.Threading.Tasks.Task<APITestCallResponse> APITestCallAsync(APITestCallRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestOCNLATA", ReplyAction="*")]
    System.Threading.Tasks.Task<RequestOCNLATAResponse> RequestOCNLATAAsync(RequestOCNLATARequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class APITestCallRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="APITestCall", Namespace="http://tempuri.org/", Order=0)]
    public APITestCallRequestBody Body;
    
    public APITestCallRequest()
    {
    }
    
    public APITestCallRequest(APITestCallRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class APITestCallRequestBody
{
    
    public APITestCallRequestBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class APITestCallResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="APITestCallResponse", Namespace="http://tempuri.org/", Order=0)]
    public APITestCallResponseBody Body;
    
    public APITestCallResponse()
    {
    }
    
    public APITestCallResponse(APITestCallResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class APITestCallResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string APITestCallResult;
    
    public APITestCallResponseBody()
    {
    }
    
    public APITestCallResponseBody(string APITestCallResult)
    {
        this.APITestCallResult = APITestCallResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class RequestOCNLATARequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOCNLATA", Namespace="http://tempuri.org/", Order=0)]
    public RequestOCNLATARequestBody Body;
    
    public RequestOCNLATARequest()
    {
    }
    
    public RequestOCNLATARequest(RequestOCNLATARequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class RequestOCNLATARequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string wsusername;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string wspassword;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string tn;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string strdate;
    
    public RequestOCNLATARequestBody()
    {
    }
    
    public RequestOCNLATARequestBody(string wsusername, string wspassword, string tn, string strdate)
    {
        this.wsusername = wsusername;
        this.wspassword = wspassword;
        this.tn = tn;
        this.strdate = strdate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class RequestOCNLATAResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestOCNLATAResponse", Namespace="http://tempuri.org/", Order=0)]
    public RequestOCNLATAResponseBody Body;
    
    public RequestOCNLATAResponse()
    {
    }
    
    public RequestOCNLATAResponse(RequestOCNLATAResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public partial class RequestOCNLATAResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public tempuri.org.OCNLATAResult2[] RequestOCNLATAResult;
    
    public RequestOCNLATAResponseBody()
    {
    }
    
    public RequestOCNLATAResponseBody(tempuri.org.OCNLATAResult2[] RequestOCNLATAResult)
    {
        this.RequestOCNLATAResult = RequestOCNLATAResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public interface OCNLATAdipSoapChannel : OCNLATAdipSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
public partial class OCNLATAdipSoapClient : System.ServiceModel.ClientBase<OCNLATAdipSoap>, OCNLATAdipSoap
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public OCNLATAdipSoapClient(EndpointConfiguration endpointConfiguration) : 
            base(OCNLATAdipSoapClient.GetBindingForEndpoint(endpointConfiguration), OCNLATAdipSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OCNLATAdipSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(OCNLATAdipSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OCNLATAdipSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(OCNLATAdipSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public OCNLATAdipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<APITestCallResponse> OCNLATAdipSoap.APITestCallAsync(APITestCallRequest request)
    {
        return base.Channel.APITestCallAsync(request);
    }
    
    public System.Threading.Tasks.Task<APITestCallResponse> APITestCallAsync()
    {
        APITestCallRequest inValue = new APITestCallRequest();
        inValue.Body = new APITestCallRequestBody();
        return ((OCNLATAdipSoap)(this)).APITestCallAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<RequestOCNLATAResponse> OCNLATAdipSoap.RequestOCNLATAAsync(RequestOCNLATARequest request)
    {
        return base.Channel.RequestOCNLATAAsync(request);
    }
    
    public System.Threading.Tasks.Task<RequestOCNLATAResponse> RequestOCNLATAAsync(string wsusername, string wspassword, string tn, string strdate)
    {
        RequestOCNLATARequest inValue = new RequestOCNLATARequest();
        inValue.Body = new RequestOCNLATARequestBody();
        inValue.Body.wsusername = wsusername;
        inValue.Body.wspassword = wspassword;
        inValue.Body.tn = tn;
        inValue.Body.strdate = strdate;
        return ((OCNLATAdipSoap)(this)).RequestOCNLATAAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public new virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.OCNLATAdipSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.OCNLATAdipSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
            httpBindingElement.AllowCookies = true;
            httpBindingElement.MaxBufferSize = int.MaxValue;
            httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.OCNLATAdipSoap))
        {
            return new System.ServiceModel.EndpointAddress("http://www.endstream.com/endstreamws/OCNLATAdip.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.OCNLATAdipSoap12))
        {
            return new System.ServiceModel.EndpointAddress("http://www.endstream.com/endstreamws/OCNLATAdip.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    public enum EndpointConfiguration
    {
        
        OCNLATAdipSoap,
        
        OCNLATAdipSoap12,
    }
}
