//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCom
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.1pcom.net/", ConfigurationName="FirstCom.DIDManagementSoap")]
    public interface DIDManagementSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDWebserviceHeartbeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDWebserviceHeartbeatResponse> DIDWebserviceHeartbeatAsync(FirstCom.DIDWebserviceHeartbeatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDAPIVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDAPIVersionResponse> DIDAPIVersionAsync(FirstCom.DIDAPIVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDOrderResponse> DIDOrderAsync(FirstCom.DIDOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDOrderBulkPattern", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDOrderBulkPatternResponse> DIDOrderBulkPatternAsync(FirstCom.DIDOrderBulkPatternRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDSMSEnable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDSMSEnableResponse> DIDSMSEnableAsync(FirstCom.DIDSMSEnableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDInventorySearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDInventorySearchResponse> DIDInventorySearchAsync(FirstCom.DIDInventorySearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDInventoryGetAvailableCities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableCitiesResponse> DIDInventoryGetAvailableCitiesAsync(FirstCom.DIDInventoryGetAvailableCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDInventoryGetAvailableStates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableStatesResponse> DIDInventoryGetAvailableStatesAsync(FirstCom.DIDInventoryGetAvailableStatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDInventoryGetAvailableNumbersByCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableNumbersByCityResponse> DIDInventoryGetAvailableNumbersByCityAsync(FirstCom.DIDInventoryGetAvailableNumbersByCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDInventoryGetAvailableCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableCountriesResponse> DIDInventoryGetAvailableCountriesAsync(FirstCom.DIDInventoryGetAvailableCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/LongCodeSearchInAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.LongCodeSearchInAccountResponse> LongCodeSearchInAccountAsync(FirstCom.LongCodeSearchInAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDSearchInAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDSearchInAccountResponse> DIDSearchInAccountAsync(FirstCom.DIDSearchInAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDDeleteFromAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDDeleteFromAccountResponse> DIDDeleteFromAccountAsync(FirstCom.DIDDeleteFromAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteVoiceToGatewayBasic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteVoiceToGatewayBasicResponse> DIDRouteVoiceToGatewayBasicAsync(FirstCom.DIDRouteVoiceToGatewayBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteVoiceToRCFBasic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteVoiceToRCFBasicResponse> DIDRouteVoiceToRCFBasicAsync(FirstCom.DIDRouteVoiceToRCFBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/LongCodeShowRouting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.LongCodeShowRoutingResponse> LongCodeShowRoutingAsync(FirstCom.LongCodeShowRoutingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteSMSToEPIDBasic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToEPIDBasicResponse> DIDRouteSMSToEPIDBasicAsync(FirstCom.DIDRouteSMSToEPIDBasicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDUnrouteSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDUnrouteSMSResponse> DIDUnrouteSMSAsync(FirstCom.DIDUnrouteSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteSMSToEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToEmailResponse> DIDRouteSMSToEmailAsync(FirstCom.DIDRouteSMSToEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteSMSToXMPP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToXMPPResponse> DIDRouteSMSToXMPPAsync(FirstCom.DIDRouteSMSToXMPPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteSMSToPUSHAPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToPUSHAPIResponse> DIDRouteSMSToPUSHAPIAsync(FirstCom.DIDRouteSMSToPUSHAPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.1pcom.net/DIDRouteSMSToPullAPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToPullAPIResponse> DIDRouteSMSToPullAPIAsync(FirstCom.DIDRouteSMSToPullAPIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDWebserviceHeartbeat", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDWebserviceHeartbeatRequest
    {
        
        public DIDWebserviceHeartbeatRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDWebserviceHeartbeatResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDWebserviceHeartbeatResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public string DIDWebserviceHeartbeatResult;
        
        public DIDWebserviceHeartbeatResponse()
        {
        }
        
        public DIDWebserviceHeartbeatResponse(string DIDWebserviceHeartbeatResult)
        {
            this.DIDWebserviceHeartbeatResult = DIDWebserviceHeartbeatResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class QueryResult
    {
        
        private int codeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class SMSLongcodeRoute
    {
        
        private string routeField;
        
        private int epidField;
        
        private string epnameField;
        
        private string eptypeField;
        
        private string additionalField;
        
        private QueryResult queryResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string route
        {
            get
            {
                return this.routeField;
            }
            set
            {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int epid
        {
            get
            {
                return this.epidField;
            }
            set
            {
                this.epidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string epname
        {
            get
            {
                return this.epnameField;
            }
            set
            {
                this.epnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string eptype
        {
            get
            {
                return this.eptypeField;
            }
            set
            {
                this.eptypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string additional
        {
            get
            {
                return this.additionalField;
            }
            set
            {
                this.additionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public QueryResult QueryResult
        {
            get
            {
                return this.queryResultField;
            }
            set
            {
                this.queryResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class LongcodeInfo
    {
        
        private string longcodeField;
        
        private string rateCenterField;
        
        private string nPAField;
        
        private string nXXField;
        
        private bool inInventoryField;
        
        private bool inAccountField;
        
        private QueryResult queryResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Longcode
        {
            get
            {
                return this.longcodeField;
            }
            set
            {
                this.longcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RateCenter
        {
            get
            {
                return this.rateCenterField;
            }
            set
            {
                this.rateCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NPA
        {
            get
            {
                return this.nPAField;
            }
            set
            {
                this.nPAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NXX
        {
            get
            {
                return this.nXXField;
            }
            set
            {
                this.nXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool InInventory
        {
            get
            {
                return this.inInventoryField;
            }
            set
            {
                this.inInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool InAccount
        {
            get
            {
                return this.inAccountField;
            }
            set
            {
                this.inAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public QueryResult QueryResult
        {
            get
            {
                return this.queryResultField;
            }
            set
            {
                this.queryResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class LongcodeInfoArray
    {
        
        private LongcodeInfo[] longcodeInfoField;
        
        private QueryResult queryresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LongcodeInfo[] LongcodeInfo
        {
            get
            {
                return this.longcodeInfoField;
            }
            set
            {
                this.longcodeInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QueryResult queryresult
        {
            get
            {
                return this.queryresultField;
            }
            set
            {
                this.queryresultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class DIDOrderInfo
    {
        
        private string dIDField;
        
        private string rateCenterField;
        
        private string nPAField;
        
        private string nXXField;
        
        private bool inInventoryField;
        
        private string planNameField;
        
        private string requiresChannelTypeField;
        
        private QueryResult queryResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RateCenter
        {
            get
            {
                return this.rateCenterField;
            }
            set
            {
                this.rateCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NPA
        {
            get
            {
                return this.nPAField;
            }
            set
            {
                this.nPAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NXX
        {
            get
            {
                return this.nXXField;
            }
            set
            {
                this.nXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool InInventory
        {
            get
            {
                return this.inInventoryField;
            }
            set
            {
                this.inInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PlanName
        {
            get
            {
                return this.planNameField;
            }
            set
            {
                this.planNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RequiresChannelType
        {
            get
            {
                return this.requiresChannelTypeField;
            }
            set
            {
                this.requiresChannelTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public QueryResult QueryResult
        {
            get
            {
                return this.queryResultField;
            }
            set
            {
                this.queryResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class DIDOrderInfoArray
    {
        
        private DIDOrderInfo[] dIDOrderField;
        
        private QueryResult queryresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DIDOrderInfo[] DIDOrder
        {
            get
            {
                return this.dIDOrderField;
            }
            set
            {
                this.dIDOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QueryResult queryresult
        {
            get
            {
                return this.queryresultField;
            }
            set
            {
                this.queryresultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class DIDOrderQuery
    {
        
        private string rateCenterField;
        
        private string nPAField;
        
        private string nXXField;
        
        private string dIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RateCenter
        {
            get
            {
                return this.rateCenterField;
            }
            set
            {
                this.rateCenterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NPA
        {
            get
            {
                return this.nPAField;
            }
            set
            {
                this.nPAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NXX
        {
            get
            {
                return this.nXXField;
            }
            set
            {
                this.nXXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.1pcom.net/")]
    public partial class Credentials
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDAPIVersion", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDAPIVersionRequest
    {
        
        public DIDAPIVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDAPIVersionResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDAPIVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDAPIVersionResult;
        
        public DIDAPIVersionResponse()
        {
        }
        
        public DIDAPIVersionResponse(FirstCom.QueryResult DIDAPIVersionResult)
        {
            this.DIDAPIVersionResult = DIDAPIVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDOrder", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public bool SMSEnable;
        
        public DIDOrderRequest()
        {
        }
        
        public DIDOrderRequest(FirstCom.Credentials Auth, string DID, bool SMSEnable)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.SMSEnable = SMSEnable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDOrderResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDOrderResult;
        
        public DIDOrderResponse()
        {
        }
        
        public DIDOrderResponse(FirstCom.QueryResult DIDOrderResult)
        {
            this.DIDOrderResult = DIDOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDOrderBulkPattern", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDOrderBulkPatternRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public FirstCom.DIDOrderQuery DIDPattern;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public bool SMSEnable;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=3)]
        public int amount;
        
        public DIDOrderBulkPatternRequest()
        {
        }
        
        public DIDOrderBulkPatternRequest(FirstCom.Credentials Auth, FirstCom.DIDOrderQuery DIDPattern, bool SMSEnable, int amount)
        {
            this.Auth = Auth;
            this.DIDPattern = DIDPattern;
            this.SMSEnable = SMSEnable;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDOrderBulkPatternResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDOrderBulkPatternResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDOrderBulkPatternResult;
        
        public DIDOrderBulkPatternResponse()
        {
        }
        
        public DIDOrderBulkPatternResponse(FirstCom.QueryResult DIDOrderBulkPatternResult)
        {
            this.DIDOrderBulkPatternResult = DIDOrderBulkPatternResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDSMSEnable", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDSMSEnableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        public DIDSMSEnableRequest()
        {
        }
        
        public DIDSMSEnableRequest(FirstCom.Credentials Auth, string DID)
        {
            this.Auth = Auth;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDSMSEnableResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDSMSEnableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDSMSEnableResult;
        
        public DIDSMSEnableResponse()
        {
        }
        
        public DIDSMSEnableResponse(FirstCom.QueryResult DIDSMSEnableResult)
        {
            this.DIDSMSEnableResult = DIDSMSEnableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventorySearch", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventorySearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public FirstCom.DIDOrderQuery DIDSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public int ReturnAmount;
        
        public DIDInventorySearchRequest()
        {
        }
        
        public DIDInventorySearchRequest(FirstCom.Credentials Auth, FirstCom.DIDOrderQuery DIDSearch, int ReturnAmount)
        {
            this.Auth = Auth;
            this.DIDSearch = DIDSearch;
            this.ReturnAmount = ReturnAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventorySearchResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventorySearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.DIDOrderInfoArray DIDInventorySearchResult;
        
        public DIDInventorySearchResponse()
        {
        }
        
        public DIDInventorySearchResponse(FirstCom.DIDOrderInfoArray DIDInventorySearchResult)
        {
            this.DIDInventorySearchResult = DIDInventorySearchResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://api.1pcom.net/")]
    public partial class DIDInventoryGetAvailableCitiesResponseDIDInventoryGetAvailableCitiesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableCities", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableCitiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string state;
        
        public DIDInventoryGetAvailableCitiesRequest()
        {
        }
        
        public DIDInventoryGetAvailableCitiesRequest(FirstCom.Credentials Auth, string state)
        {
            this.Auth = Auth;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableCitiesResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableCitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.DIDInventoryGetAvailableCitiesResponseDIDInventoryGetAvailableCitiesResult DIDInventoryGetAvailableCitiesResult;
        
        public DIDInventoryGetAvailableCitiesResponse()
        {
        }
        
        public DIDInventoryGetAvailableCitiesResponse(FirstCom.DIDInventoryGetAvailableCitiesResponseDIDInventoryGetAvailableCitiesResult DIDInventoryGetAvailableCitiesResult)
        {
            this.DIDInventoryGetAvailableCitiesResult = DIDInventoryGetAvailableCitiesResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://api.1pcom.net/")]
    public partial class DIDInventoryGetAvailableStatesResponseDIDInventoryGetAvailableStatesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableStates", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableStatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string country;
        
        public DIDInventoryGetAvailableStatesRequest()
        {
        }
        
        public DIDInventoryGetAvailableStatesRequest(FirstCom.Credentials Auth, string country)
        {
            this.Auth = Auth;
            this.country = country;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableStatesResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableStatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.DIDInventoryGetAvailableStatesResponseDIDInventoryGetAvailableStatesResult DIDInventoryGetAvailableStatesResult;
        
        public DIDInventoryGetAvailableStatesResponse()
        {
        }
        
        public DIDInventoryGetAvailableStatesResponse(FirstCom.DIDInventoryGetAvailableStatesResponseDIDInventoryGetAvailableStatesResult DIDInventoryGetAvailableStatesResult)
        {
            this.DIDInventoryGetAvailableStatesResult = DIDInventoryGetAvailableStatesResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://api.1pcom.net/")]
    public partial class DIDInventoryGetAvailableNumbersByCityResponseDIDInventoryGetAvailableNumbersByCityResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableNumbersByCity", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableNumbersByCityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string city;
        
        public DIDInventoryGetAvailableNumbersByCityRequest()
        {
        }
        
        public DIDInventoryGetAvailableNumbersByCityRequest(FirstCom.Credentials Auth, string city)
        {
            this.Auth = Auth;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableNumbersByCityResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableNumbersByCityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.DIDInventoryGetAvailableNumbersByCityResponseDIDInventoryGetAvailableNumbersByCityResult DIDInventoryGetAvailableNumbersByCityResult;
        
        public DIDInventoryGetAvailableNumbersByCityResponse()
        {
        }
        
        public DIDInventoryGetAvailableNumbersByCityResponse(FirstCom.DIDInventoryGetAvailableNumbersByCityResponseDIDInventoryGetAvailableNumbersByCityResult DIDInventoryGetAvailableNumbersByCityResult)
        {
            this.DIDInventoryGetAvailableNumbersByCityResult = DIDInventoryGetAvailableNumbersByCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableCountries", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableCountriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        public DIDInventoryGetAvailableCountriesRequest()
        {
        }
        
        public DIDInventoryGetAvailableCountriesRequest(FirstCom.Credentials Auth)
        {
            this.Auth = Auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDInventoryGetAvailableCountriesResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDInventoryGetAvailableCountriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public string[] DIDInventoryGetAvailableCountriesResult;
        
        public DIDInventoryGetAvailableCountriesResponse()
        {
        }
        
        public DIDInventoryGetAvailableCountriesResponse(string[] DIDInventoryGetAvailableCountriesResult)
        {
            this.DIDInventoryGetAvailableCountriesResult = DIDInventoryGetAvailableCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LongCodeSearchInAccount", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class LongCodeSearchInAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public FirstCom.DIDOrderQuery DIDSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public int ReturnAmount;
        
        public LongCodeSearchInAccountRequest()
        {
        }
        
        public LongCodeSearchInAccountRequest(FirstCom.Credentials Auth, FirstCom.DIDOrderQuery DIDSearch, int ReturnAmount)
        {
            this.Auth = Auth;
            this.DIDSearch = DIDSearch;
            this.ReturnAmount = ReturnAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LongCodeSearchInAccountResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class LongCodeSearchInAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.LongcodeInfoArray LongCodeSearchInAccountResult;
        
        public LongCodeSearchInAccountResponse()
        {
        }
        
        public LongCodeSearchInAccountResponse(FirstCom.LongcodeInfoArray LongCodeSearchInAccountResult)
        {
            this.LongCodeSearchInAccountResult = LongCodeSearchInAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDSearchInAccount", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDSearchInAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public FirstCom.DIDOrderQuery DIDSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public int ReturnAmount;
        
        public DIDSearchInAccountRequest()
        {
        }
        
        public DIDSearchInAccountRequest(FirstCom.Credentials Auth, FirstCom.DIDOrderQuery DIDSearch, int ReturnAmount)
        {
            this.Auth = Auth;
            this.DIDSearch = DIDSearch;
            this.ReturnAmount = ReturnAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDSearchInAccountResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDSearchInAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.DIDOrderInfoArray DIDSearchInAccountResult;
        
        public DIDSearchInAccountResponse()
        {
        }
        
        public DIDSearchInAccountResponse(FirstCom.DIDOrderInfoArray DIDSearchInAccountResult)
        {
            this.DIDSearchInAccountResult = DIDSearchInAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDDeleteFromAccount", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDDeleteFromAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string did;
        
        public DIDDeleteFromAccountRequest()
        {
        }
        
        public DIDDeleteFromAccountRequest(FirstCom.Credentials Auth, string did)
        {
            this.Auth = Auth;
            this.did = did;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDDeleteFromAccountResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDDeleteFromAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDDeleteFromAccountResult;
        
        public DIDDeleteFromAccountResponse()
        {
        }
        
        public DIDDeleteFromAccountResponse(FirstCom.QueryResult DIDDeleteFromAccountResult)
        {
            this.DIDDeleteFromAccountResult = DIDDeleteFromAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteVoiceToGatewayBasic", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteVoiceToGatewayBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public string GatewayIP;
        
        public DIDRouteVoiceToGatewayBasicRequest()
        {
        }
        
        public DIDRouteVoiceToGatewayBasicRequest(FirstCom.Credentials Auth, string DID, string GatewayIP)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.GatewayIP = GatewayIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteVoiceToGatewayBasicResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteVoiceToGatewayBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteVoiceToGatewayBasicResult;
        
        public DIDRouteVoiceToGatewayBasicResponse()
        {
        }
        
        public DIDRouteVoiceToGatewayBasicResponse(FirstCom.QueryResult DIDRouteVoiceToGatewayBasicResult)
        {
            this.DIDRouteVoiceToGatewayBasicResult = DIDRouteVoiceToGatewayBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteVoiceToRCFBasic", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteVoiceToRCFBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string did;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public string RouteToNumber;
        
        public DIDRouteVoiceToRCFBasicRequest()
        {
        }
        
        public DIDRouteVoiceToRCFBasicRequest(FirstCom.Credentials Auth, string did, string RouteToNumber)
        {
            this.Auth = Auth;
            this.did = did;
            this.RouteToNumber = RouteToNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteVoiceToRCFBasicResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteVoiceToRCFBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteVoiceToRCFBasicResult;
        
        public DIDRouteVoiceToRCFBasicResponse()
        {
        }
        
        public DIDRouteVoiceToRCFBasicResponse(FirstCom.QueryResult DIDRouteVoiceToRCFBasicResult)
        {
            this.DIDRouteVoiceToRCFBasicResult = DIDRouteVoiceToRCFBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LongCodeShowRouting", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class LongCodeShowRoutingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string LongCode;
        
        public LongCodeShowRoutingRequest()
        {
        }
        
        public LongCodeShowRoutingRequest(FirstCom.Credentials Auth, string LongCode)
        {
            this.Auth = Auth;
            this.LongCode = LongCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LongCodeShowRoutingResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class LongCodeShowRoutingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.SMSLongcodeRoute LongCodeShowRoutingResult;
        
        public LongCodeShowRoutingResponse()
        {
        }
        
        public LongCodeShowRoutingResponse(FirstCom.SMSLongcodeRoute LongCodeShowRoutingResult)
        {
            this.LongCodeShowRoutingResult = LongCodeShowRoutingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToEPIDBasic", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToEPIDBasicRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public int EPID;
        
        public DIDRouteSMSToEPIDBasicRequest()
        {
        }
        
        public DIDRouteSMSToEPIDBasicRequest(FirstCom.Credentials Auth, string DID, int EPID)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.EPID = EPID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToEPIDBasicResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToEPIDBasicResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteSMSToEPIDBasicResult;
        
        public DIDRouteSMSToEPIDBasicResponse()
        {
        }
        
        public DIDRouteSMSToEPIDBasicResponse(FirstCom.QueryResult DIDRouteSMSToEPIDBasicResult)
        {
            this.DIDRouteSMSToEPIDBasicResult = DIDRouteSMSToEPIDBasicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDUnrouteSMS", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDUnrouteSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        public DIDUnrouteSMSRequest()
        {
        }
        
        public DIDUnrouteSMSRequest(FirstCom.Credentials Auth, string DID)
        {
            this.Auth = Auth;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDUnrouteSMSResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDUnrouteSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDUnrouteSMSResult;
        
        public DIDUnrouteSMSResponse()
        {
        }
        
        public DIDUnrouteSMSResponse(FirstCom.QueryResult DIDUnrouteSMSResult)
        {
            this.DIDUnrouteSMSResult = DIDUnrouteSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToEmail", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public string emailaddress;
        
        public DIDRouteSMSToEmailRequest()
        {
        }
        
        public DIDRouteSMSToEmailRequest(FirstCom.Credentials Auth, string DID, string emailaddress)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.emailaddress = emailaddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToEmailResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteSMSToEmailResult;
        
        public DIDRouteSMSToEmailResponse()
        {
        }
        
        public DIDRouteSMSToEmailResponse(FirstCom.QueryResult DIDRouteSMSToEmailResult)
        {
            this.DIDRouteSMSToEmailResult = DIDRouteSMSToEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToXMPP", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToXMPPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public string XMPPUser;
        
        public DIDRouteSMSToXMPPRequest()
        {
        }
        
        public DIDRouteSMSToXMPPRequest(FirstCom.Credentials Auth, string DID, string XMPPUser)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.XMPPUser = XMPPUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToXMPPResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToXMPPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteSMSToXMPPResult;
        
        public DIDRouteSMSToXMPPResponse()
        {
        }
        
        public DIDRouteSMSToXMPPResponse(FirstCom.QueryResult DIDRouteSMSToXMPPResult)
        {
            this.DIDRouteSMSToXMPPResult = DIDRouteSMSToXMPPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToPUSHAPI", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToPUSHAPIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=2)]
        public string URL;
        
        public DIDRouteSMSToPUSHAPIRequest()
        {
        }
        
        public DIDRouteSMSToPUSHAPIRequest(FirstCom.Credentials Auth, string DID, string URL)
        {
            this.Auth = Auth;
            this.DID = DID;
            this.URL = URL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToPUSHAPIResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToPUSHAPIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteSMSToPUSHAPIResult;
        
        public DIDRouteSMSToPUSHAPIResponse()
        {
        }
        
        public DIDRouteSMSToPUSHAPIResponse(FirstCom.QueryResult DIDRouteSMSToPUSHAPIResult)
        {
            this.DIDRouteSMSToPUSHAPIResult = DIDRouteSMSToPUSHAPIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToPullAPI", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToPullAPIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.Credentials Auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=1)]
        public string DID;
        
        public DIDRouteSMSToPullAPIRequest()
        {
        }
        
        public DIDRouteSMSToPullAPIRequest(FirstCom.Credentials Auth, string DID)
        {
            this.Auth = Auth;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DIDRouteSMSToPullAPIResponse", WrapperNamespace="https://api.1pcom.net/", IsWrapped=true)]
    public partial class DIDRouteSMSToPullAPIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.1pcom.net/", Order=0)]
        public FirstCom.QueryResult DIDRouteSMSToPullAPIResult;
        
        public DIDRouteSMSToPullAPIResponse()
        {
        }
        
        public DIDRouteSMSToPullAPIResponse(FirstCom.QueryResult DIDRouteSMSToPullAPIResult)
        {
            this.DIDRouteSMSToPullAPIResult = DIDRouteSMSToPullAPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DIDManagementSoapChannel : FirstCom.DIDManagementSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DIDManagementSoapClient : System.ServiceModel.ClientBase<FirstCom.DIDManagementSoap>, FirstCom.DIDManagementSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DIDManagementSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DIDManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), DIDManagementSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIDManagementSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DIDManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIDManagementSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DIDManagementSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DIDManagementSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDWebserviceHeartbeatResponse> DIDWebserviceHeartbeatAsync(FirstCom.DIDWebserviceHeartbeatRequest request)
        {
            return base.Channel.DIDWebserviceHeartbeatAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDAPIVersionResponse> DIDAPIVersionAsync(FirstCom.DIDAPIVersionRequest request)
        {
            return base.Channel.DIDAPIVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDOrderResponse> DIDOrderAsync(FirstCom.DIDOrderRequest request)
        {
            return base.Channel.DIDOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDOrderBulkPatternResponse> DIDOrderBulkPatternAsync(FirstCom.DIDOrderBulkPatternRequest request)
        {
            return base.Channel.DIDOrderBulkPatternAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDSMSEnableResponse> DIDSMSEnableAsync(FirstCom.DIDSMSEnableRequest request)
        {
            return base.Channel.DIDSMSEnableAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDInventorySearchResponse> DIDInventorySearchAsync(FirstCom.DIDInventorySearchRequest request)
        {
            return base.Channel.DIDInventorySearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableCitiesResponse> DIDInventoryGetAvailableCitiesAsync(FirstCom.DIDInventoryGetAvailableCitiesRequest request)
        {
            return base.Channel.DIDInventoryGetAvailableCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableStatesResponse> DIDInventoryGetAvailableStatesAsync(FirstCom.DIDInventoryGetAvailableStatesRequest request)
        {
            return base.Channel.DIDInventoryGetAvailableStatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableNumbersByCityResponse> DIDInventoryGetAvailableNumbersByCityAsync(FirstCom.DIDInventoryGetAvailableNumbersByCityRequest request)
        {
            return base.Channel.DIDInventoryGetAvailableNumbersByCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDInventoryGetAvailableCountriesResponse> DIDInventoryGetAvailableCountriesAsync(FirstCom.DIDInventoryGetAvailableCountriesRequest request)
        {
            return base.Channel.DIDInventoryGetAvailableCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.LongCodeSearchInAccountResponse> LongCodeSearchInAccountAsync(FirstCom.LongCodeSearchInAccountRequest request)
        {
            return base.Channel.LongCodeSearchInAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDSearchInAccountResponse> DIDSearchInAccountAsync(FirstCom.DIDSearchInAccountRequest request)
        {
            return base.Channel.DIDSearchInAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDDeleteFromAccountResponse> DIDDeleteFromAccountAsync(FirstCom.DIDDeleteFromAccountRequest request)
        {
            return base.Channel.DIDDeleteFromAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteVoiceToGatewayBasicResponse> DIDRouteVoiceToGatewayBasicAsync(FirstCom.DIDRouteVoiceToGatewayBasicRequest request)
        {
            return base.Channel.DIDRouteVoiceToGatewayBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteVoiceToRCFBasicResponse> DIDRouteVoiceToRCFBasicAsync(FirstCom.DIDRouteVoiceToRCFBasicRequest request)
        {
            return base.Channel.DIDRouteVoiceToRCFBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.LongCodeShowRoutingResponse> LongCodeShowRoutingAsync(FirstCom.LongCodeShowRoutingRequest request)
        {
            return base.Channel.LongCodeShowRoutingAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToEPIDBasicResponse> DIDRouteSMSToEPIDBasicAsync(FirstCom.DIDRouteSMSToEPIDBasicRequest request)
        {
            return base.Channel.DIDRouteSMSToEPIDBasicAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDUnrouteSMSResponse> DIDUnrouteSMSAsync(FirstCom.DIDUnrouteSMSRequest request)
        {
            return base.Channel.DIDUnrouteSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToEmailResponse> DIDRouteSMSToEmailAsync(FirstCom.DIDRouteSMSToEmailRequest request)
        {
            return base.Channel.DIDRouteSMSToEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToXMPPResponse> DIDRouteSMSToXMPPAsync(FirstCom.DIDRouteSMSToXMPPRequest request)
        {
            return base.Channel.DIDRouteSMSToXMPPAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToPUSHAPIResponse> DIDRouteSMSToPUSHAPIAsync(FirstCom.DIDRouteSMSToPUSHAPIRequest request)
        {
            return base.Channel.DIDRouteSMSToPUSHAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirstCom.DIDRouteSMSToPullAPIResponse> DIDRouteSMSToPullAPIAsync(FirstCom.DIDRouteSMSToPullAPIRequest request)
        {
            return base.Channel.DIDRouteSMSToPullAPIAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DIDManagementSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DIDManagementSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DIDManagementSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.1pcom.net/ws2/DIDManagement.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DIDManagementSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.1pcom.net/ws2/DIDManagement.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DIDManagementSoap,
            
            DIDManagementSoap12,
        }
    }
}
