using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

using NumberSearch.DataAccess;
using NumberSearch.DataAccess.FusionPBX;
using NumberSearch.Mvc.Models;

using PhoneNumbersNA;

using System.Collections.Concurrent;
using System.ComponentModel.DataAnnotations;

using ZLinq;

namespace NumberSearch.Mvc.Controllers
{
    public static class Endpoints
    {
        /// <summary>
        /// Represents the result of a bulk number lookup operation.
        /// </summary>
        /// <param name="DialedNumber"></param>
        /// <param name="City"></param>
        /// <param name="State"></param>
        /// <param name="DateIngested"></param>
        /// <param name="Wireless"></param>
        /// <param name="Portable"></param>
        /// <param name="LastPorted"></param>
        /// <param name="SPID"></param>
        /// <param name="LATA"></param>
        /// <param name="LEC"></param>
        /// <param name="LECType"></param>
        /// <param name="LIDBName"></param>
        /// <param name="LRN"></param>
        /// <param name="OCN"></param>
        /// <param name="CarrierName"></param>
        /// <param name="CarrierLogoLink"></param>
        /// <param name="CarrierColor"></param>
        /// <param name="CarrierType"></param>
        public readonly record struct BulkLookupResult(string DialedNumber, string City, string State, DateTime DateIngested, bool Wireless, bool Portable, DateTime LastPorted, string SPID, string LATA, string LEC, string LECType, string LIDBName, string LRN, string OCN, string CarrierName, string CarrierLogoLink, string CarrierColor, string CarrierType);

        /// <summary>
        /// Authenticates a token against the API keys generated by existing user accounts in FusionPBX.
        /// </summary>
        /// <param name="token">An API key generated by a user account in FusionPBX.</param>
        /// <param name="mvcConfiguration">The configuration for the application.</param>
        /// <returns>The matching enabled FusionPBX user, or a default User if the token is invalid.</returns>
        public static async Task<User> AuthenticateFusionPBXApiKeyAsync(string token, MvcConfiguration mvcConfiguration)
        {
            if (string.IsNullOrWhiteSpace(token) || string.IsNullOrWhiteSpace(mvcConfiguration.FusionPBXConnectionString))
            {
                return default;
            }

            var user = await User.GetByApiKeyAsync(token.AsMemory(), mvcConfiguration.FusionPBXConnectionString.AsMemory());

            // FusionPBX stores user_enabled as the text 'true' or 'false' rather than as a boolean.
            return user.user_uuid != Guid.Empty && user.user_enabled is "true" ? user : default;
        }

        /// <summary>
        /// Performs a bulk lookup for dialed phone numbers.
        /// </summary>
        /// <param name="token">The authentication token for the request, either an API key generated by your user account in FusionPBX or the legacy shared token.</param>
        /// <param name="dialedNumber">A comma-separated list of dialed phone numbers to look up.</param>
        /// <param name="mvcConfiguration">The configuration for the application.</param>
        /// <returns></returns>
        public static async Task<Results<Ok<BulkLookupResult[]>, BadRequest<string>>> NumberSearchBulkAsync([Required] string token, [Required] string dialedNumber, [FromServices] MvcConfiguration mvcConfiguration)
        {
            var fusionPBXUser = await AuthenticateFusionPBXApiKeyAsync(token, mvcConfiguration);

            if (fusionPBXUser.user_uuid != Guid.Empty || (!string.IsNullOrWhiteSpace(token) && token == "Memorable8142024"))
            {
                // Add portable numbers to cart in bulk
                if (!string.IsNullOrWhiteSpace(dialedNumber))
                {
                    var parsedNumbers = dialedNumber.ExtractDialedNumbers().ToArray();

                    if (parsedNumbers.Length == 0)
                    {
                        return TypedResults.BadRequest("No dialed phone numbers found. Please try a different query.");
                    }

                    var results = new ConcurrentBag<PortedPhoneNumber>();
                    await Parallel.ForEachAsync(parsedNumbers, async (number, token) =>
                    {
                        var lookup = new LookupController(mvcConfiguration);
                        var result = await lookup.VerifyPortabilityAsync(number);
                        results.Add(result);
                    });

                    var lookups = new List<BulkLookupResult>(results.Count);
                    foreach (var number in results)
                    {
                        lookups.Add(new BulkLookupResult(number.PortedDialedNumber, number.City, number.State, number.DateIngested, number.Wireless, number.Portable, number.LrnLookup.LastPorted, number.LrnLookup.SPID, number.LrnLookup.LATA, number.LrnLookup.LEC, number.LrnLookup.LECType, number.LrnLookup.LIDBName, number.LrnLookup.LRN, number.LrnLookup.OCN, number.Carrier.Name, number.Carrier.LogoLink, number.Carrier.Color, number.Carrier.Type));
                    }

                    return TypedResults.Ok(lookups.ToArray());
                }
                else
                {
                    return TypedResults.BadRequest("No dialed phone numbers found. Please try a different query.");
                }
            }
            else
            {
                return TypedResults.BadRequest("Token is invalid. Please supply the correct token in your request or contact support@acceleratenetworks.com for help.");
            }
        }

        /// <summary>
        /// Represents a phone number related to a FusionPBX user account.
        /// </summary>
        /// <param name="DialedNumber"></param>
        /// <param name="Description"></param>
        /// <param name="Enabled"></param>
        /// <param name="Type"></param>
        public readonly record struct ClientNumber(string DialedNumber, string Description, bool Enabled, string Type);

        /// <summary>
        /// Gets the phone numbers related to the authenticated user's account, based on the destinations registered to their domain in FusionPBX.
        /// </summary>
        /// <param name="token">An API key generated by your user account in FusionPBX.</param>
        /// <param name="mvcConfiguration">The configuration for the application.</param>
        /// <returns>An array of ClientNumbers.</returns>
        public static async Task<Results<Ok<ClientNumber[]>, BadRequest<string>>> ClientNumbersAsync([Required] string token, [FromServices] MvcConfiguration mvcConfiguration)
        {
            var fusionPBXUser = await AuthenticateFusionPBXApiKeyAsync(token, mvcConfiguration);

            if (fusionPBXUser.user_uuid == Guid.Empty)
            {
                return TypedResults.BadRequest("Token is invalid. Please supply the correct token in your request or contact support@acceleratenetworks.com for help.");
            }

            var destinations = await DestinationDetails.GetByDomainIdAsync(fusionPBXUser.domain_uuid ?? Guid.Empty, mvcConfiguration.FusionPBXConnectionString.AsMemory());

            var numbers = destinations.AsValueEnumerable()
                .Where(x => !string.IsNullOrWhiteSpace(x.destination_number))
                .Select(x => new ClientNumber(x.destination_number, x.destination_description, x.destination_enabled, x.destination_type))
                .ToArray();

            return TypedResults.Ok(numbers);
        }

        /// <summary>
        /// Performs a bulk lookup for dialed phone numbers that are related to the authenticated user's account.
        /// Only numbers registered as destinations in the user's FusionPBX domain are looked up, any other numbers in the query are ignored.
        /// Numbers match even when supplied with a country code prefix, so +12065551234 and 12065551234 both match a destination stored as 2065551234.
        /// </summary>
        /// <param name="token">An API key generated by your user account in FusionPBX.</param>
        /// <param name="dialedNumber">A comma-separated list of dialed phone numbers related to your user account.</param>
        /// <param name="mvcConfiguration">The configuration for the application.</param>
        /// <returns></returns>
        public static async Task<Results<Ok<BulkLookupResult[]>, BadRequest<string>>> ClientNumberSearchAsync([Required] string token, [Required] string dialedNumber, [FromServices] MvcConfiguration mvcConfiguration)
        {
            var fusionPBXUser = await AuthenticateFusionPBXApiKeyAsync(token, mvcConfiguration);

            if (fusionPBXUser.user_uuid == Guid.Empty)
            {
                return TypedResults.BadRequest("Token is invalid. Please supply the correct token in your request or contact support@acceleratenetworks.com for help.");
            }

            var parsedNumbers = dialedNumber.ExtractDialedNumbers().ToArray();

            if (parsedNumbers.Length == 0)
            {
                return TypedResults.BadRequest("No dialed phone numbers found. Please try a different query.");
            }

            // Restrict the lookup to phone numbers that are destinations in the authenticated user's domain.
            var relatedNumbers = new ConcurrentBag<string>();
            await Parallel.ForEachAsync(parsedNumbers, async (number, token) =>
            {
                var destination = await DestinationDetails.GetByDialedNumberAndDomainAsync(number.AsMemory(), fusionPBXUser.domain_uuid ?? Guid.Empty, mvcConfiguration.FusionPBXConnectionString.AsMemory());
                if (destination.destination_uuid != Guid.Empty)
                {
                    relatedNumbers.Add(number);
                }
            });

            if (relatedNumbers.IsEmpty)
            {
                return TypedResults.BadRequest("No dialed phone numbers related to your user account found. Please try a different query.");
            }

            var results = new ConcurrentBag<PortedPhoneNumber>();
            await Parallel.ForEachAsync(relatedNumbers, async (number, token) =>
            {
                var lookup = new LookupController(mvcConfiguration);
                var result = await lookup.VerifyPortabilityAsync(number);
                results.Add(result);
            });

            var lookups = new List<BulkLookupResult>(results.Count);
            foreach (var number in results)
            {
                lookups.Add(new BulkLookupResult(number.PortedDialedNumber, number.City, number.State, number.DateIngested, number.Wireless, number.Portable, number.LrnLookup.LastPorted, number.LrnLookup.SPID, number.LrnLookup.LATA, number.LrnLookup.LEC, number.LrnLookup.LECType, number.LrnLookup.LIDBName, number.LrnLookup.LRN, number.LrnLookup.OCN, number.Carrier.Name, number.Carrier.LogoLink, number.Carrier.Color, number.Carrier.Type));
            }

            return TypedResults.Ok(lookups.ToArray());
        }

        /// <summary>
        /// A service we can sell at an address.
        /// </summary>
        /// <param name="product">WFI (fiber internet) or EIA (ethernet internet access).</param>
        /// <param name="status">Sellable (add to cart at the listed price), Confirm (contact us to confirm availability), or Quote (custom priced, request a quote).</param>
        /// <param name="name">The name of the service.</param>
        /// <param name="speed">The symmetrical speed of the service.</param>
        /// <param name="price">The monthly price in dollars, or 0 when the price must be quoted.</param>
        /// <param name="serviceId">The ServiceId to add to the cart, or empty when it can't be added to the cart directly.</param>
        /// <param name="note">Terms and details to show alongside the service.</param>
        public readonly record struct InternetOffer(string product, string status, string name, string speed, int price, Guid serviceId, string note);

        /// <summary>
        /// The services available at an address.
        /// </summary>
        /// <param name="serviceable">Whether any service is available at the address.</param>
        /// <param name="matchedAddress">The address from the provider's building list that matched the query.</param>
        /// <param name="offers">The services available at the address.</param>
        public readonly record struct InternetAvailability(bool serviceable, string matchedAddress, InternetOffer[] offers);

        public static readonly Guid FiberInternet300ServiceId = new("cbcf5128-5164-40de-8dff-e71d0f152cab");
        public static readonly Guid FiberInternet1GServiceId = new("708c3885-6dab-4a60-9e42-05cf13530076");
        private const string FiberTerms = "2, 3 or 5 year term. $15/mo off when bundled with any phone service.";

        /// <summary>
        /// Look up the internet services we can sell at an address, using the building lists from our providers.
        /// </summary>
        /// <param name="houseNumber">The house or building number, ex. 1250</param>
        /// <param name="street">The street name without the direction or suffix, ex. 1st</param>
        /// <param name="postal">The 5 digit ZIP code, ex. 98134</param>
        /// <param name="latitude">The latitude of the address, used when the street address doesn't match exactly.</param>
        /// <param name="longitude">The longitude of the address, used when the street address doesn't match exactly.</param>
        /// <param name="mvcConfiguration">The configuration for the application.</param>
        /// <returns>The services available at the address.</returns>
        public static async Task<Results<Ok<InternetAvailability>, BadRequest<string>>> InternetAvailabilityAsync(string? houseNumber, string? street, string? postal, double? latitude, double? longitude, [FromServices] MvcConfiguration mvcConfiguration)
        {
            if ((string.IsNullOrWhiteSpace(houseNumber) || string.IsNullOrWhiteSpace(street) || string.IsNullOrWhiteSpace(postal)) && (latitude is null || longitude is null))
            {
                return TypedResults.BadRequest("Provide a houseNumber, street, and postal code or a latitude and longitude (ex: houseNumber=1250&street=1st&postal=98134). Please try a different query. 🥺👉👈");
            }

            var addresses = (await ServiceAddress.LookupAsync(houseNumber ?? string.Empty, street ?? string.Empty, postal ?? string.Empty, latitude ?? 0, longitude ?? 0, mvcConfiguration.PostgresqlProd)).ToArray();
            var offers = new List<InternetOffer>();

            var wfi = addresses.AsValueEnumerable().Where(x => x.Product is "WFI").ToArray();
            if (wfi.AsValueEnumerable().Any(x => x.Status is "Sellable"))
            {
                offers.Add(new("WFI", "Sellable", "Fiber Internet 300 Mbps", "300/300 Mbps", 75, FiberInternet300ServiceId, FiberTerms));
                if (wfi.AsValueEnumerable().Any(x => x.Status is "Sellable" && x.MaxSpeed.StartsWith("1.0G")))
                {
                    offers.Add(new("WFI", "Sellable", "Fiber Internet 1 Gbps", "1/1 Gbps", 115, FiberInternet1GServiceId, FiberTerms));
                }
            }
            else if (wfi.Length > 0)
            {
                offers.Add(new("WFI", "Confirm", "Fiber Internet", "Up to 1/1 Gbps", 0, Guid.Empty, "Fiber may be available here. Contact us to confirm before ordering."));
            }

            if (addresses.AsValueEnumerable().Any(x => x.Product is "EIA" && x.Status is "Quote"))
            {
                offers.Add(new("EIA", "Quote", "Ethernet Internet Access", "Dedicated, custom speeds", 0, Guid.Empty, "Dedicated fiber with an SLA. Contact us for a quote."));
            }

            var matched = addresses.AsValueEnumerable().Select(x => $"{x.StreetAddress.Trim()}, {x.City}, {x.State} {x.Postal}").FirstOrDefault() ?? string.Empty;
            return TypedResults.Ok(new InternetAvailability(offers.Count > 0, matched, offers.ToArray()));
        }

        /// <summary>
        /// https://www.twilio.com/docs/lookup/v2-api
        /// </summary>
        /// <param name="calling_country_code">International dialing prefix of the phone number defined in the E.164 standard.</param>
        /// <param name="country_code">The phone number's ISO country code.</param>
        /// <param name="phone_number">The phone number in E.164 format, which consists of a + followed by the country code and subscriber number.</param>
        /// <param name="national_format">The phone number in national format.</param>
        /// <param name="valid">Boolean which indicates if the phone number is in a valid range that can be freely assigned by a carrier to a user.</param>
        /// <param name="validation_errors">Contains reasons why a phone number is invalid. Possible values: TOO_SHORT, TOO_LONG, INVALID_BUT_POSSIBLE, INVALID_COUNTRY_CODE, INVALID_LENGTH, NOT_A_NUMBER.</param>
        /// <param name="caller_name">An object that contains caller name information based on CNAM.</param>
        /// <param name="sim_swap">An object that contains information on the last date the subscriber identity module (SIM) was changed for a mobile phone number.</param>
        /// <param name="call_forwarding">An object that contains information on the unconditional call forwarding status of mobile phone number.</param>
        /// <param name="line_status">An object that contains line status information for a mobile phone number.</param>
        /// <param name="line_type_intelligence">An object that contains line type information including the carrier name, mobile country code, and mobile network code.</param>
        /// <param name="identity_match">An object that contains identity match information. The result of comparing user-provided information including name, address, date of birth, national ID, against authoritative phone-based data sources.</param>
        /// <param name="reassigned_number">An object that contains reassigned number information. Reassigned Numbers will return a phone number's reassignment status given a phone number and date.</param>
        /// <param name="sms_pumping_risk">An object that contains information on if a phone number has been currently or previously blocked by Verify Fraud Guard for receiving malicious SMS pumping traffic as well as other signals associated with risky carriers and low conversion rates.</param>
        /// <param name="phone_number_quality_score">An object that contains information of a mobile phone number quality score. Quality score will return a risk score about the phone number.</param>
        /// <param name="pre_fill">An object that contains pre fill information. pre_fill will return PII information associated with the phone number like first name, last name, address line, country code, state and postal code.</param>
        /// <param name="url">The absolute URL of the resource.</param>
        public readonly record struct NumberLookupResponse(
             string calling_country_code,
             string country_code,
             string phone_number,
             string national_format,
             bool valid,
             string[] validation_errors,
             CallerName? caller_name,
             SimSwap? sim_swap,
             CallForwarding? call_forwarding,
             LineStatus? line_status,
             LineTypeIntelligence? line_type_intelligence,
             IdentityMatch? identity_match,
             ReassignedNumber? reassigned_number,
             SmsPumpingRisk? sms_pumping_risk,
             object? phone_number_quality_score,
             object? pre_fill,
             string url
        );

        /// <summary>
        /// https://www.twilio.com/docs/lookup/v2-api/line-type-intelligence
        /// </summary>
        /// <param name="mobile_country_code">The three-digit mobile country code of the carrier, used with the mobile_network_code to identify a mobile network operator.</param>
        /// <param name="mobile_network_code">The two- or three-digit mobile network code of the carrier, used with the mobile country code to identify a mobile network operator. This is only returned for mobile numbers.</param>
        /// <param name="carrier_name">The name of the carrier.</param>
        /// <param name="type">	The phone number type.</param>
        /// <param name="error_code">The error code. If there's no error, this value will be null.</param>
        public readonly record struct LineTypeIntelligence(string mobile_country_code, string mobile_network_code, string carrier_name, string type, int? error_code);
        /// <summary>
        /// https://www.twilio.com/docs/lookup/v2-api/caller-name
        /// </summary>
        /// <param name="caller_name">The name of the owner of the phone number. If not available, this will be null.</param>
        /// <param name="caller_type">The caller type. Possible values are BUSINESS and CONSUMER. If not available, this will be null.</param>
        /// <param name="error_code">The error code, if any, associated with your request.</param>
        public readonly record struct CallerName(string caller_name, string caller_type, int? error_code);
        public readonly record struct SimSwap(LastSimSwap last_sim_swap, string carrier_name, string mobile_country_code, string mobile_network_code, int error_code);
        public readonly record struct LastSimSwap(DateTime last_sim_swap_date, string swapped_period, bool swapped_in_period);
        public readonly record struct CallForwarding(bool call_forwarding_enabled, int error_code);
        public readonly record struct ReassignedNumber(string is_number_reassigned, int error_code);
        public readonly record struct LineStatus(string status, int error_code);
        public readonly record struct IdentityMatch(bool identity_match, int error_code);
        /// <summary>
        /// https://www.twilio.com/docs/lookup/v2-api/sms-pumping-risk
        /// </summary>
        /// <param name="carrier_risk_category">The risk category of the carrier based on its score. Available values are high, moderate, mild, and low.</param>
        /// <param name="number_blocked">A Boolean indicating whether the phone number is currently blocked by Verify Fraud Guard for receiving malicious SMS pumping traffic.</param>
        /// <param name="number_blocked_date">The most recent date the phone number was blocked by Verify Fraud Guard. Returns null if the phone number has never been blocked or processed by Verify Fraud Guard.</param>
        /// <param name="number_blocked_last_3_months">A Boolean indicating whether the phone number has been blocked by Verify Fraud Guard in the last three months. Returns null if the phone number has never been processed by Verify Fraud Guard.</param>
        /// <param name="sms_pumping_risk_score">The risk score for the phone number, calculated from patterns in messaging traffic. Ranges from 0 (no risk) to 100 (high risk).</param>
        /// <param name="error_code">The error code, if any, associated with your request.</param>
        public readonly record struct SmsPumpingRisk(string carrier_risk_category, bool number_blocked, DateTime? number_blocked_date, bool? number_blocked_last_3_months, int sms_pumping_risk_score, int error_code);

        public static async Task<Results<Ok<NumberLookupResponse>, BadRequest<string>>> LookupAPIV2([Required] string PhoneNumber, string? Fields, [FromServices] MvcConfiguration mvcConfiguration)
        {
            if (string.IsNullOrWhiteSpace(Fields))
            {
                return TypedResults.BadRequest("Fields parameter is required. Ex: Fields=line_type_intelligence or Fields=caller_name");
            }

            string[] fieldsArray = Fields.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

            if (Fields is "line_type_intelligence")
            {
                return TypedResults.Ok(new NumberLookupResponse(
                    calling_country_code: "+1",
                    country_code: "US",
                    phone_number: PhoneNumber,
                    national_format: "(555) 555-5555",
                    valid: true,
                    validation_errors: Array.Empty<string>(),
                    caller_name: null,
                    sim_swap: null,
                    call_forwarding: null,
                    line_status: null,
                    line_type_intelligence: new LineTypeIntelligence("310", "260", "T-Mobile", "mobile", null),
                    identity_match: null,
                    reassigned_number: null,
                    sms_pumping_risk: null,
                    phone_number_quality_score: null,
                    pre_fill: null,
                    url: $"https://api.example.com/lookup/v2/phone_numbers/{PhoneNumber}?fields=line_type_intelligence"
                ));
            }
            else if (Fields is "caller_name")
            {
                return TypedResults.Ok(new NumberLookupResponse(
                    calling_country_code: "+1",
                    country_code: "US",
                    phone_number: PhoneNumber,
                    national_format: "(555) 555-5555",
                    valid: true,
                    validation_errors: Array.Empty<string>(),
                    caller_name: new CallerName("John Doe", "CONSUMER", null),
                    sim_swap: null,
                    call_forwarding: null,
                    line_status: null,
                    line_type_intelligence: null,
                    identity_match: null,
                    reassigned_number: null,
                    sms_pumping_risk: null,
                    phone_number_quality_score: null,
                    pre_fill: null,
                    url: $"https://api.example.com/lookup/v2/phone_numbers/{PhoneNumber}?fields=caller_name"
                ));
            }
            else if (Fields is "sim_swap")
            {
                return TypedResults.BadRequest("Fields sim_swap is not supported.");
            }
            else if (Fields is "call_forwarding")
            {
                return TypedResults.BadRequest("Fields call_forwarding is not supported.");
            }
            else if (Fields is "line_status")
            {
                return TypedResults.BadRequest("Fields line_status is not supported.");
            }
            else if (Fields is "identity_match")
            {
                return TypedResults.BadRequest("Fields identity_match is not supported.");
            }
            else if (Fields is "reassigned_number")
            {
                return TypedResults.BadRequest("Fields reassigned_number is not supported.");
            }
            else if (Fields is "sms_pumping_risk")
            {
                return TypedResults.BadRequest("Fields sms_pumping_risk is not supported.");
            }
            else
            {
                return TypedResults.BadRequest("Invalid Fields parameter. Please specify a valid field to look up.");
            }
        }
    }
}
